# Generated by Django 5.0.14 on 2025-08-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialworkmodel',
            name='head_erpid',
            field=models.IntegerField(default=0),
        ),
    ]
