# Generated by Django 5.0.14 on 2025-09-25 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officialwork', '0002_officialworkmodel_head_erpid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='officialworkmodel',
            table='dbo.official_work_leaves',
        ),
    ]
