# Generated by Django 5.0.14 on 2025-09-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officialwork', '0003_alter_officialworkmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='officialworkmodel',
            table='official_work_leaves',
        ),
    ]
