# Generated by Django 5.0.14 on 2026-01-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialwork', '0004_alter_officialworkmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialworkmodel',
            name='approved_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
