# Generated by Django 5.0.14 on 2025-08-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemodel',
            name='head_erpid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavemodel',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
