# Generated by Django 5.0.14 on 2026-01-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leavemodel_head_erpid_alter_leavemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemodel',
            name='approved_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
