# Generated by Django 5.0.14 on 2026-03-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_category_alter_letter_options_letter_assigned_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('monthly_day', 'Specific Day of Each Month'), ('first_weekday', 'First Weekday of Every Month'), ('quarterly', 'Quarterly ')], max_length=30, null=True),
        ),
    ]
